
exclude:

    # Exclude list and detail pages, since they rarely change and take a long time to build.
    - list
    - community-garden
    - community-garden
    - farmers-market
    - food-bank
    - grocery-store
    - supermarket

    # These files are unique to the “site” repository.
    - rakefile

keep_files:

    # Keep the list and detail pages, if they exist.
    - list
    - community-garden
    - community-garden
    - farmers-market
    - food-bank
    - grocery-store
    - supermarket

    # These files are unique to the “foodoasisla.github.io” repository.
    - .nojekyll
    - .gitignore
    - .git
