# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Food Oasis
email: fooddesertsla@gmail.com
description: >
  This website was put together during the Civic Hack Nights at hackforla.org, a part of http://codeforamerica.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tamurafatherree.github.io/fooddesert/" # the base hostname & protocol for your site
github_username: tamurafatherree

# Build settings
markdown: kramdown
