
# Exclude list and detail pages, since they rarely change and take a long time to build.

exclude:
    - rakefile
    - list
    - community-garden
    - community-garden
    - farmers-market
    - food-bank
    - grocery-store
    - supermarket

keep_files:
    - CNAME
    - .nojekyll
    - .git
    - rakefile
    - list
    - community-garden
    - community-garden
    - farmers-market
    - food-bank
    - grocery-store
    - supermarket
