# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Food Oasis Los Angeles
email: fooddesertsla@gmail.com
description: >
  This website was put together during the Civic Hack Nights at hackforla.org, a part of http://codeforamerica.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://foodoasisla.github.io" # the base hostname & protocol for your site
github_username: foodoasisla

exclude:
    - CNAME
    - .nojekyll
    - .git
    - rakefile

keep_files:
    - CNAME
    - .nojekyll
    - .git
    - rakefile
